Config = {}

Config.EnableDamageModifier = true

Config.WeaponsDamageModifier = {
	[`WEAPON_UNARMED`]				    = {Hash = `WEAPON_UNARMED`,                	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_DAGGER`] 				    = {Hash = `WEAPON_DAGGER`, 			 		DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_BAT`] 					    = {Hash = `WEAPON_BAT`, 			 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_BOTTLE`] 				    = {Hash = `WEAPON_BOTTLE`, 			 		DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_CROWBAR`] 				    = {Hash = `WEAPON_CROWBAR`, 		 	  	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_FLASHLIGHT`]			    = {Hash = `WEAPON_FLASHLIGHT`,				DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_GOLFCLUB`] 			    = {Hash = `WEAPON_GOLFCLUB`, 		 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_HAMMER`] 				    = {Hash = `WEAPON_HAMMER`, 			 		DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_HATCHET`] 				    = {Hash = `WEAPON_HATCHET`, 		 	  	DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_KNUCKLE`] 				    = {Hash = `WEAPON_KNUCKLE`, 		 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_KNIFE`] 				    = {Hash = `WEAPON_KNIFE`, 			 	  	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_MACHETE`] 				    = {Hash = `WEAPON_MACHETE`, 		 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_SWITCHBLADE`] 			    = {Hash = `WEAPON_SWITCHBLADE`, 	 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_NIGHTSTICK`] 			    = {Hash = `WEAPON_NIGHTSTICK`, 		 		DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_WRENCH`] 				    = {Hash = `WEAPON_WRENCH`, 			 		DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_BATTLEAXE`] 			    = {Hash = `WEAPON_BATTLEAXE`, 		 	  	DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_POOLCUE`] 				    = {Hash = `WEAPON_POOLCUE`, 		 	  	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_STONE_HATCHET`] 		    = {Hash = `WEAPON_STONE_HATCHET`, 		   	DamageModifier = 0.3, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_PISTOL`] 				    = {Hash = `WEAPON_PISTOL`, 			 		DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_PISTOL_MK2`] 			    = {Hash = `WEAPON_PISTOL_MK2`, 				DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_COMBATPISTOL`] 		    = {Hash = `WEAPON_COMBATPISTOL`, 	 	  	DamageModifier = 0.8, 		DisableCriticalHit = false},
	[`WEAPON_APPISTOL`] 			    = {Hash = `WEAPON_APPISTOL`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_PISTOL50`] 			    = {Hash = `WEAPON_PISTOL50`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_SNSPISTOL`] 			    = {Hash = `WEAPON_SNSPISTOL`, 		 	  	DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_SNSPISTOL_MK2`] 		    = {Hash = `WEAPON_SNSPISTOL_MK2`, 	 	  	DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_HEAVYPISTOL`] 			    = {Hash = `WEAPON_HEAVYPISTOL`, 	 	  	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_VINTAGEPISTOL`] 		    = {Hash = `WEAPON_VINTAGEPISTOL`, 	 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_FLAREGUN`] 			    = {Hash = `WEAPON_FLAREGUN`, 		 	  	DamageModifier = 0.0, 		DisableCriticalHit = false},
	[`WEAPON_MARKSMANPISTOL`] 		    = {Hash = `WEAPON_MARKSMANPISTOL`, 	 		DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_REVOLVER`] 			    = {Hash = `WEAPON_REVOLVER`, 		 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_REVOLVER_MK2`] 		    = {Hash = `WEAPON_REVOLVER_MK2`, 		  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_DOUBLEACTION`] 		    = {Hash = `WEAPON_DOUBLEACTION`, 		  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_CERAMICPISTOL`] 		    = {Hash = `WEAPON_CERAMICPISTOL`, 		 	DamageModifier = 0.9, 		DisableCriticalHit = false},
	[`WEAPON_NAVYREVOLVER`] 		    = {Hash = `WEAPON_NAVYREVOLVER`, 		  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_GADGETPISTOL`] 		    = {Hash = `WEAPON_GADGETPISTOL`, 	 		DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_RAYPISTOL`] 			    = {Hash = `WEAPON_RAYPISTOL`, 	 			DamageModifier = 1.0, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_MICROSMG`] 			    = {Hash = `WEAPON_MICROSMG`, 		 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_SMG`] 				 	    = {Hash = `WEAPON_SMG`, 			 	  	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_SMG_MK2`] 			 	    = {Hash = `WEAPON_SMG_MK2`, 			   	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_ASSAULTSMG`] 			    = {Hash = `WEAPON_ASSAULTSMG`, 		 		DamageModifier = 0.8, 		DisableCriticalHit = false},
	[`WEAPON_COMBATPDW`] 			    = {Hash = `WEAPON_COMBATPDW`, 		 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_MACHINEPISTOL`] 		    = {Hash = `WEAPON_MACHINEPISTOL`, 	 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_MINISMG`] 				    = {Hash = `WEAPON_MINISMG`, 		 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_RAYCARBINE`] 			    = {Hash = `WEAPON_RAYCARBINE`, 	 			DamageModifier = 1.0, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_PUMPSHOTGUN`] 			    = {Hash = `WEAPON_PUMPSHOTGUN`, 	 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_PUMPSHOTGUN_MK2`] 		    = {Hash = `WEAPON_PUMPSHOTGUN_MK2`, 	   	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_SAWNOFFSHOTGUN`] 		    = {Hash = `WEAPON_SAWNOFFSHOTGUN`, 	 		DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_ASSAULTSHOTGUN`] 		    = {Hash = `WEAPON_ASSAULTSHOTGUN`, 	 		DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_BULLPUPSHOTGUN`] 		    = {Hash = `WEAPON_BULLPUPSHOTGUN`, 	 		DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_MUSKET`] 			        = {Hash = `WEAPON_MUSKET`, 			 		DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_HEAVYSHOTGUN`] 		    = {Hash = `WEAPON_HEAVYSHOTGUN`, 	 	  	DamageModifier = 0.3, 		DisableCriticalHit = false},
	[`WEAPON_DBSHOTGUN`] 			    = {Hash = `WEAPON_DBSHOTGUN`, 		 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_AUTOSHOTGUN`] 			    = {Hash = `WEAPON_AUTOSHOTGUN`, 	 	  	DamageModifier = 0.2, 		DisableCriticalHit = false},
	[`WEAPON_COMBATSHOTGUN`] 		    = {Hash = `WEAPON_COMBATSHOTGUN`, 	 	  	DamageModifier = 0.3, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_HEAVYRIFLE`] 		 	    = {Hash = `WEAPON_HEAVYRIFLE`, 	 	  		DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_ASSAULTRIFLE`] 		    = {Hash = `WEAPON_ASSAULTRIFLE`, 	 	  	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_ASSAULTRIFLE_MK2`] 	    = {Hash = `WEAPON_ASSAULTRIFLE_MK2`, 	   	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_CARBINERIFLE`] 		    = {Hash = `WEAPON_CARBINERIFLE`, 	 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_CARBINERIFLE_MK2`] 	    = {Hash = `WEAPON_CARBINERIFLE_MK2`, 		DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_ADVANCEDRIFLE`] 		    = {Hash = `WEAPON_ADVANCEDRIFLE`, 	 	  	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_SPECIALCARBINE`] 		    = {Hash = `WEAPON_SPECIALCARBINE`, 	 		DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_SPECIALCARBINE_MK2`] 	    = {Hash = `WEAPON_SPECIALCARBINE_MK2`,  	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_BULLPUPRIFLE`] 		    = {Hash = `WEAPON_BULLPUPRIFLE`, 	 	  	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_BULLPUPRIFLE_MK2`] 	    = {Hash = `WEAPON_BULLPUPRIFLE_MK2`, 	   	DamageModifier = 0.6, 		DisableCriticalHit = false},
	[`WEAPON_COMPACTRIFLE`] 		    = {Hash = `WEAPON_COMPACTRIFLE`, 	 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_MILITARYRIFLE`] 		    = {Hash = `WEAPON_MILITARYRIFLE`, 	 	  	DamageModifier = 0.8, 		DisableCriticalHit = false},
	[`WEAPON_HEAVYRIFLE`] 			    = {Hash = `WEAPON_HEAVYRIFLE`, 				DamageModifier = 3.0, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_MG`] 					    = {Hash = `WEAPON_MG`, 				 		DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_COMBATMG`] 			    = {Hash = `WEAPON_COMBATMG`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_COMBATMG_MK2`] 		    = {Hash = `WEAPON_COMBATMG_MK2`, 	 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_GUSENBERG`] 			    = {Hash = `WEAPON_GUSENBERG`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_SNIPERRIFLE`] 			    = {Hash = `WEAPON_SNIPERRIFLE`, 	 	  	DamageModifier = 0.7, 		DisableCriticalHit = false},
	[`WEAPON_HEAVYSNIPER`] 			    = {Hash = `WEAPON_HEAVYSNIPER`, 	 	  	DamageModifier = 0.8, 		DisableCriticalHit = false},
	[`WEAPON_HEAVYSNIPER_MK2`] 		    = {Hash = `WEAPON_HEAVYSNIPER_MK2`, 	  	DamageModifier = 0.8, 		DisableCriticalHit = false},
	[`WEAPON_MARKSMANRIFLE`] 		    = {Hash = `WEAPON_MARKSMANRIFLE`, 	 	  	DamageModifier = 0.8, 		DisableCriticalHit = false},
	[`WEAPON_MARKSMANRIFLE_MK2`] 	    = {Hash = `WEAPON_MARKSMANRIFLE_MK2`, 	   	DamageModifier = 0.8, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_RPG`] 					    = {Hash = `WEAPON_RPG`, 			      	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_GRENADELAUNCHER`] 		    = {Hash = `WEAPON_GRENADELAUNCHER`, 	  	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_GRENADELAUNCHER_SMOKE`]    = {Hash = `WEAPON_GRENADELAUNCHER_SMOKE`, 	DamageModifier = 0.0, 		DisableCriticalHit = false},
	[`WEAPON_MINIGUN`] 				    = {Hash = `WEAPON_MINIGUN`, 		      	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_FIREWORK`] 			    = {Hash = `WEAPON_FIREWORK`, 		 	  	DamageModifier = 0.0, 		DisableCriticalHit = false},
	[`WEAPON_RAILGUN`] 				    = {Hash = `WEAPON_RAILGUN`, 		 	  	DamageModifier = 1.0, 		DisableCriticalHit = false},
	[`WEAPON_HOMINGLAUNCHER`] 		    = {Hash = `WEAPON_HOMINGLAUNCHER`, 	 		DamageModifier = 0.4, 		DisableCriticalHit = false},
	[`WEAPON_COMPACTLAUNCHER`] 		    = {Hash = `WEAPON_COMPACTLAUNCHER`,  	  	DamageModifier = 0.4, 		DisableCriticalHit = false},
	[`WEAPON_RAYMINIGUN`] 			    = {Hash = `WEAPON_RAYMINIGUN`, 		   		DamageModifier = 1.0, 		DisableCriticalHit = false},
	[`WEAPON_EMPLAUNCHER`] 			    = {Hash = `WEAPON_EMPLAUNCHER`, 			DamageModifier = 1.0, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_GRENADE`] 				    = {Hash = `WEAPON_GRENADE`, 		      	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_BZGAS`] 				    = {Hash = `WEAPON_BZGAS`, 			      	DamageModifier = 0.1, 		DisableCriticalHit = false},
	[`WEAPON_MOLOTOV`] 				    = {Hash = `WEAPON_MOLOTOV`, 		      	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_STICKYBOMB`] 			    = {Hash = `WEAPON_STICKYBOMB`, 		    	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_PROXMINE`] 			    = {Hash = `WEAPON_PROXMINE`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_PIPEBOMB`] 			    = {Hash = `WEAPON_PIPEBOMB`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_SMOKEGRENADE`] 		    = {Hash = `WEAPON_SMOKEGRENADE`, 	      	DamageModifier = 0.0, 		DisableCriticalHit = false},
	[`WEAPON_FLARE`] 				    = {Hash = `WEAPON_FLARE`, 			 	  	DamageModifier = 0.0, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_STUNGUN_MP`] 			    = {Hash = `WEAPON_STUNGUN_MP`, 		 		DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_STUNGUN`] 				    = {Hash = `WEAPON_STUNGUN`, 		 	  	DamageModifier = 0.5, 		DisableCriticalHit = false},
	[`WEAPON_FIREEXTINGUISHER`] 	    = {Hash = `WEAPON_FIREEXTINGUISHER`,      	DamageModifier = 0.5, 		DisableCriticalHit = false},
	-- //
	[`WEAPON_BALL`] 				    = {Hash = `WEAPON_BALL`, 			 	  	DamageModifier = 0.0, 		DisableCriticalHit = false},
	[`WEAPON_SNOWBALL`] 		        = {Hash = `WEAPON_SNOWBALL`, 		 	  	DamageModifier = 0.0, 		DisableCriticalHit = false}
}